// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// This pipeline builds the Docker image which will be used as env for cloud-ws jobs.
// It uses Kaniko to avoid docker in docker privilege issues.
//
// References:
//   * https://github.com/GoogleContainerTools/kaniko

pipeline {
  // Parameters defined in workloads/cloud-workstations/pipelines/environment/docker-image-template/groovy/job.groovy

  agent {
    kubernetes {
      yaml """\
        apiVersion: v1
        kind: Pod
        spec:
          hostname: jenkins-cloud-ws-env-pod
          serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            imagePullPolicy: IfNotPresent
            command:
            - /busybox/cat
            tty: true
      """.stripIndent()
    }
  }

  // Block concurrent builds to avoid clashing.
  options {
    buildBlocker (useBuildBlocker: true, blockLevel: 'GLOBAL', scanQueueFor: 'BUILDABLE', blockingJobs: '(?i)Cloud-Workstations/.*/Docker.*')
  }

  environment {
    // Update latest tag.
    DESTINATION="--destination=${env.CLOUD_REGION}-docker.pkg.dev/${env.CLOUD_PROJECT}/${env.CLOUD_WS_WORKLOADS_ENV_IMAGE_NAME}"
    KANIKO_OPTIONS="${NO_PUSH == "true" ? "--no-push" : "${DESTINATION}:${IMAGE_TAG}"}"
  }

  stages {
    stage ('Create Docker Image'){
      when { expression { env.IMAGE_TAG } }
      steps {
        container(name: 'kaniko') {
          script {
            currentBuild.description = "NO_PUSH=${env.NO_PUSH}" + "<br>" + "$BUILD_USER"
          }
          sh '''
            # Build the docker image and push to Artifact registry using service account configured with
            # correct roles/permissions.
            /kaniko/executor -f workloads/cloud-workstations/pipelines/environment/docker-image-template/Dockerfile \
              -c workloads/cloud-workstations/pipelines/environment/docker-image-template --skip-tls-verify-pull \
              --insecure --skip-tls-verify "${KANIKO_OPTIONS}"
          '''
        }
      }
    }
  }
}