// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Create a development instance that developers can connect to for a finite
// time, allowing them to develop builds and investigate issues.

pipeline {

  agent none

  environment {
    // Define Pod Template in environment so we may override later if needs be.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          openbsw_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: openbsw
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: openbsw_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-openbsw-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${OPENBSW_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: IfNotPresent
          command:
          - sleep
          args:
          - 5h
        nodeSelector:
          workloadLabel: openbsw
    """.stripIndent()
  }

  stages {
    stage ('Start VM Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Retain instance') {
          when { expression { env.INSTANCE_MAX_UPTIME } }
          steps {
            container(name: 'builder') {
              script {
                sleep(time: "${INSTANCE_MAX_UPTIME}", unit: 'HOURS')
              }
            }
          }
        }
      }
    }
  }
}
