// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Jenkins pipeline to retrieve ABFS Cloud Spanner environment details.
// - Reports bucket sizes, Spanner instances, backups, and backup schedules.
// - Optional filters: ABFS_DB_BUCKET_NAME (bucket name), ABFS_DB_NAME (instance
//                     name substring)
// The script uses strict mode and safe loops; gcloud must be authenticated with
// proper IAM.

pipeline {

  agent none

  environment {

    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      spec:
        hostname: jenkins-abfs-spanner-details-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: abfs-spanner-details
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${INFRA_DOCKER_ARTIFACT_PATH_NAME}:${INFRA_IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sleep
          args:
          - 5h
          tty: true
    """.stripIndent()
  }



  stages {
    stage ('Start Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Get Spanner Details') {
          steps {
            script {
              currentBuild.description = "$BUILD_USER"
            }
            container(name: 'abfs-spanner-details') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd ./workloads/android/pipelines/environment/abfs/server_administration/get_spanner_details/
                  ABFS_BUCKET_NAME=${ABFS_BUCKET_NAME} \
                  ABFS_DB_NAME=${ABS_DB_NAME} \
                  ./get_spanner_details.sh
                '''
                archiveArtifacts artifacts: '*status*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }
      }
    }
  }
}
