// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// AAOS Build targets pipeline.

pipeline {

  agent none

  environment {

    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      spec:
        hostname: jenkins-abfs-uploader-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: abfs-uploader-builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/horizon-sdv/abfs-uploader:latest
          imagePullPolicy: IfNotPresent
          command:
          - sleep
          args:
          - 5h
          tty: true
    """.stripIndent()
  }

  stages {
    stage ('Start Uploader Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Initialise') {
          steps {
            container(name: 'abfs-uploader-builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
               withCredentials([string(credentialsId: 'jenkins-abfs-license-b64', variable: "JENKINS_ABFS_LICENSE_B64")]) {
                  sh '''
                    set +x
                    cd ./workloads/android/pipelines/environment/abfs_uploader/
                    ABFS_LICENSE_B64=${JENKINS_ABFS_LICENSE_B64} ./abfs_uploader_run.sh
                  '''
                }
              }
            }
          }
        }

        stage ('Retain Uploader Instance') {
          steps {
            container(name: 'abfs-uploader-builder') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }

  post {
    aborted {
      script {
        echo "Pipeline ABORT START !!!"
        terraform plan
        sleep(time: "1", unit: 'MINUTES')
        echo "Pipeline ABORT END !!!"
      }
    }
  }
}
