// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// AAOS Build targets pipeline.

pipeline {

  agent none

  environment {

    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          abfs_uploader_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android-abfs
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: abfs_uploader_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-abfs-uploader-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: abfs-uploader
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/horizon-sdv/abfs-uploader:latest
          imagePullPolicy: IfNotPresent
          command:
          - sleep
          args:
          - 5h
        nodeSelector:
          workloadLabel: android-abfs
    """.stripIndent()
  }

  stages {
    stage ('Start Uploader Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Initialise') {
          steps {
            container(name: 'abfs-uploader') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  set +x
                  echo "Hello World !"
                '''
              }
            }
          }
        }

        stage ('Retain Uploader Instance') {
          steps {
            container(name: 'abfs-uploader') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }
}
