// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// This pipeline builds the OpenBSW builder Docker image using BuildKit.
//
// References:
//   * https://github.com/moby/buildkit
//   * Image: https://hub.docker.com/r/moby/buildkit
//     e.g. image: moby/buildkit:v0.24.0
pipeline {

  // Parameters defined in groovy/job.groovy

  agent none

  environment {
    // Update latest tag.
    REGISTRY="${env.CLOUD_REGION}-docker.pkg.dev"
    DESTINATION="${REGISTRY}/${env.CLOUD_PROJECT}/${env.OPENBSW_BUILD_DOCKER_ARTIFACT_PATH_NAME}"
    PUSH="${NO_PUSH == "true" ? "false" : "true"}"

    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          openbsw_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: openbsw
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: openbsw_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-openbsw-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: buildkit
          image: moby/buildkit:${BUILDKIT_RELEASE_TAG}
          imagePullPolicy: Always
          securityContext:
            privileged: true
        nodeSelector:
          workloadLabel: openbsw
      """.stripIndent()
  }

  stages {
    stage ('Start instance'){
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Docker Credentials'){
          steps {
            script {
              currentBuild.description = "NO_PUSH=${env.NO_PUSH}" + "<br>" + "$BUILD_USER"
            }
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  wget -nv -O docker-credential-gcr.tgz ${DOCKER_CREDENTIALS_URL}
                  tar -zxf docker-credential-gcr.tgz
                  chmod +x docker-credential-gcr && mv docker-credential-gcr /usr/bin/
                  rm -f docker-credential-gcr*.tar.gz
                  docker-credential-gcr configure-docker --registries=${REGISTRY}
                '''
              }
            }
          }
        }

        stage ('Build Docker Image'){
          when { expression { env.IMAGE_TAG } }
          steps {
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd "${WORKSPACE}/workloads/openbsw/pipelines/environment/docker_image_template/";
                  buildctl build \
                   --frontend=dockerfile.v0 \
                   --local=dockerfile=. \
                   --local context=. \
                   --opt build-arg:ABFS="false" \
                   --opt build-arg:LINUX_DISTRIBUTION=${LINUX_DISTRIBUTION} \
                   --opt build-arg:NODEJS_VERSION=${NODEJS_VERSION} \
                   --opt build-arg:ARM_TOOLCHAIN_URL=${ARM_TOOLCHAIN_URL} \
                   --opt build-arg:CLANG_TOOLS_URL=${CLANG_TOOLS_URL} \
                   --opt build-arg:CMAKE_URL=${CMAKE_URL} \
                   --opt build-arg:GCLOUD_CLI_VERSION="${GCLOUD_CLI_VERSION}" \
                   --opt build-arg:KUBECTL_VERSION="${KUBECTL_VERSION}" \
                   --opt build-arg:LLVM_PROJECT_URL=${LLVM_PROJECT_URL} \
                   --opt build-arg:LLVM_ARM_TOOLCHAIN_URL=${LLVM_ARM_TOOLCHAIN_URL} \
                   --opt build-arg:OPENBSW_GIT_URL=${OPENBSW_GIT_URL} \
                   --opt build-arg:OPENBSW_GIT_BRANCH=${OPENBSW_GIT_BRANCH} \
                   --opt build-arg:PLANTUML_URL="${PLANTUML_URL}" \
                   --opt build-arg:POST_GIT_CLONE_COMMAND="${POST_GIT_CLONE_COMMAND}" \
                   --opt build-arg:PYELFTOOLS_VERSION=${PYELFTOOLS_VERSION} \
                   --opt build-arg:PYTHON_VERSION=${PYTHON_VERSION} \
                   --opt build-arg:SSCACHE_URL=${SSCACHE_URL} \
                   --opt build-arg:TREEFMT_URL=${TREEFMT_URL} \
                   --opt platform=linux/amd64 \
                   --registry-auth-tlscontext host=${REGISTRY},insecure=true \
                   --output=type=image,name=${DESTINATION}:${IMAGE_TAG},push=${PUSH}
                '''
              }
            }
          }
        }
      }
    }
  }
}
