// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// AAOS Build targets pipeline.

pipeline {

  agent none

  environment {
    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          aaos_abfs_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android-abfs
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_abfs_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-abfs-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ABFS_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
          - sleep
          args:
          - 5h
        nodeSelector:
          workloadLabel: android-abfs
    """.stripIndent()
  }

  stages {
    stage ('Start VM Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Build'){
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_REVISION="${AAOS_REVISION}" \
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  ABFS_VERSION="${ABFS_VERSION}" \
                  ABFS_REPOSITORY="${ABFS_REPOSITORY}" \
                  ./workloads/android/pipelines/builds/aaos_abfs_builder/aaos_abfs_build.sh
                '''
              }
            }
          }
        }

        stage ('Retain instance') {
          when { expression { env.AAOS_LUNCH_TARGET } }
          steps {
            container(name: 'builder') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }
}
