
// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// OpenBSW builder.

pipeline {

  // Parameters defined in groovy/job.groovy

  agent none

  environment {
    // Define Pod Template in environment so we may override later if needs be.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          openbsw_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: openbsw
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: openbsw_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-openbsw-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${OPENBSW_BUILD_DOCKER_ARTIFACT_PATH_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command:
          - sleep
          args:
          - 4h
        nodeSelector:
          workloadLabel: openbsw
    """.stripIndent()
  }


  stages {
    stage ('Start VM Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }

      stages {
        stage ('Initialise') {
          steps {
            script {
              currentBuild.description = "$BUILD_USER" + "<br/>" + "${env.IMAGE_TAG}"
            }
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  OPENBSW_GIT_URL="${OPENBSW_GIT_URL}" \
                  OPENBSW_GIT_BRANCH="${OPENBSW_GIT_BRANCH}" \
                  POST_GIT_CLONE_COMMAND="${POST_GIT_CLONE_COMMAND}" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_initialise.sh
                '''
              }
            }
          }
        }

        stage ('List Unit Tests') {
          when {
            allOf {
              expression { env.LIST_UNIT_TESTS == 'true' }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  CMAKE_SYNC_JOBS="${CMAKE_SYNC_JOBS}" \
                  BUILD_NXP_S32K148="false" \
                  BUILD_POSIX="false" \
                  BUILD_UNIT_TESTS="false" \
                  CODE_COVERAGE="false" \
                  LIST_UNIT_TESTS="${LIST_UNIT_TESTS}" \
                  LIST_UNIT_TESTS_CMDLINE="${LIST_UNIT_TESTS_CMDLINE}" \
                  RUN_UNIT_TESTS="false" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
                archiveArtifacts artifacts: '*unit_test*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }

        stage ('Build Unit Tests') {
          when {
            allOf {
              expression { env.BUILD_UNIT_TESTS == 'true' }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  CMAKE_SYNC_JOBS="${CMAKE_SYNC_JOBS}" \
                  BUILD_NXP_S32K148="false" \
                  BUILD_POSIX="false" \
                  BUILD_UNIT_TESTS="${BUILD_UNIT_TESTS}" \
                  CODE_COVERAGE="false" \
                  LIST_UNIT_TESTS="false" \
                  RUN_UNIT_TESTS="false" \
                  UNIT_TESTS_CMDLINE="${UNIT_TESTS_CMDLINE}" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
              }
            }
          }
        }

        stage ('Run Unit Tests') {
          when {
            allOf {
              expression { env.BUILD_UNIT_TESTS == 'true' }
              expression { env.RUN_UNIT_TESTS == 'true' }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  CMAKE_SYNC_JOBS="${CMAKE_SYNC_JOBS}" \
                  BUILD_NXP_S32K148="false" \
                  BUILD_POSIX="false" \
                  BUILD_UNIT_TESTS="false" \
                  CODE_COVERAGE="false" \
                  LIST_UNIT_TESTS="false" \
                  RUN_UNIT_TESTS="${RUN_UNIT_TESTS}" \
                  RUN_UNIT_TESTS_CMDLINE="${RUN_UNIT_TESTS_CMDLINE}" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
                archiveArtifacts artifacts: '*unit_test*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }

        stage ('Code Coverage') {
          when {
            allOf {
              expression { env.BUILD_UNIT_TESTS == 'true' }
              expression { env.RUN_UNIT_TESTS == 'true' }
              expression { env.CODE_COVERAGE == 'true' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  BUILD_NXP_S32K148="false" \
                  BUILD_POSIX="false" \
                  BUILD_UNIT_TESTS="false" \
                  LIST_UNIT_TESTS="false" \
                  RUN_UNIT_TESTS="false" \
                  CODE_COVERAGE="${CODE_COVERAGE}" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
                archiveArtifacts artifacts: '*coverage.html.tgz', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true

                publishHTML target: [
                  allowMissing: true,
                  alwaysLinkToLastBuild: true,
                  keepAll: true,
                  reportDir: "coverage",
                  reportFiles: 'index.html',
                  reportName: 'OpenBSW Unit Test Coverage Report'
                ]
              }
            }
          }
        }

        stage ('Build POSIX Target') {
          when {
            allOf {
              expression { env.BUILD_POSIX == 'true' }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  CMAKE_SYNC_JOBS="${CMAKE_SYNC_JOBS}" \
                  BUILD_NXP_S32K148="false" \
                  BUILD_POSIX="${BUILD_POSIX}" \
                  BUILD_UNIT_TESTS="false" \
                  CODE_COVERAGE="false" \
                  LIST_UNIT_TESTS="false" \
                  POSIX_BUILD_CMDLINE="${POSIX_BUILD_CMDLINE}" \
                  RUN_UNIT_TESTS="false" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
              }
            }
          }
        }

        stage ('Build NXP S32K148 Target') {
          when {
            allOf {
              expression { env.BUILD_NXP_S32K148 == 'true' }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  CMAKE_SYNC_JOBS="${CMAKE_SYNC_JOBS}" \
                  BUILD_POSIX="false" \
                  BUILD_UNIT_TESTS="false" \
                  BUILD_NXP_S32K148="${BUILD_NXP_S32K148}" \
                  CODE_COVERAGE="false" \
                  LIST_UNIT_TESTS="false" \
                  NXP_S32K148_BUILD_CMDLINE="${NXP_S32K148_BUILD_CMDLINE}" \
                  RUN_UNIT_TESTS="false" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_build.sh
                '''
              }
            }
          }
        }

        stage ('Storage') {
          when {
            allOf {
              expression { env.OPENBSW_ARTIFACT_STORAGE_SOLUTION }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  OPENBSW_ARTIFACT_ROOT_NAME="${OPENBSW_BUILD_BUCKET_ROOT_NAME}" \
                  RUN_UNIT_TESTS="${RUN_UNIT_TESTS}" \
                  BUILD_POSIX="${BUILD_POSIX}" \
                  BUILD_NXP_S32K148="${BUILD_NXP_S32K148}" \
                  ./workloads/openbsw/pipelines/builds/bsw_builder/bsw_storage.sh
                '''
                archiveArtifacts artifacts: '*artifacts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }

        stage ('Retain instance') {
          when {
            allOf {
              expression { env.BUILD_UNIT_TESTS == 'true' }
              expression { env.BUILD_NXP_S32K148 == 'true' }
              expression { env.BUILD_POSIX == 'true' }
            }
          }
          steps {
            container(name: 'builder') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }
}
