// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Jenkins pipeline to retrieve ABFS server (GCE) instance details.
// - Lists instances in CLOUD_ZONE filtered by SERVER_INSTANCE_PREFIX and prints
//   their status.
// - Requires env: CLOUD_ZONE, SERVER_INSTANCE_PREFIX. Uses gcloud and the
//   Jenkins K8s agent image.

pipeline {

  agent none

  environment {

    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      spec:
        hostname: jenkins-abfs-server-details-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: abfs-server-details
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${INFRA_DOCKER_ARTIFACT_PATH_NAME}:${INFRA_IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sleep
          args:
          - 5h
          tty: true
    """.stripIndent()
  }

  stages {
    stage ('Start Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Server Details') {
          steps {
            script {
              currentBuild.description = "$BUILD_USER"
            }
            container(name: 'abfs-server-details') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd ./workloads/android/pipelines/environment/abfs/server_administration/get_server_details/
                  INSTANCE_PREFIX=${SERVER_INSTANCE_PREFIX} \
                  ZONE=${CLOUD_ZONE} \
                  LIST_BRANCHES="false" \
                  ./get_instance_details.sh
                '''
              }
              archiveArtifacts artifacts: '*status*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              archiveArtifacts artifacts: '*cloud-init*.log', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              archiveArtifacts artifacts: '*journal*.log', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
            }
          }
        }
      }
    }
  }
}
