// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Compliance Test Suite Execution on Cuttlefish Virtual Devices.
//
// On error, cleanup VM instances because the GCE plugin can lose connection
// with GCP and VM instance, leaving the instance running and that adds to
// cloud costs.

@Library('cvd-pipeline-shared-library') _

cvdPipeline(
  cleanup_container_timeout: 10,
  launcher_condition: [
    "env.CTS_TEST_LISTS_ONLY == 'false'",
    "currentBuild.currentResult == 'SUCCESS'"
  ],
  connect_condition: [
    "env.MTK_CONNECT_ENABLE == 'true'" ,
    "env.CTS_TEST_LISTS_ONLY == 'false'"
  ],
  keep_dev_alive_cond: [
    "env.MTK_CONNECT_ENABLE == 'true'",
    "env.CTS_TEST_LISTS_ONLY == 'false'"
  ],
  stop_devices_cond: [
    "env.CUTTLEFISH_DOWNLOAD_URL",
    "env.CTS_TEST_LISTS_ONLY == 'false'"
  ],
  customStageOne: [
    [
      name: 'List Tests',
      steps: {
        if (env.CTS_TEST_LISTS_ONLY == 'true') {
          script {
            currentBuild.description = "${params.JENKINS_GCE_CLOUD_LABEL}" + "<br/>" + "$BUILD_USER"
          }
          sh '''
            ANDROID_VERSION=${ANDROID_VERSION} \
            CTS_DOWNLOAD_URL="${CTS_DOWNLOAD_URL}" \
            ./workloads/android/pipelines/tests/cts_execution/cts_initialise.sh
            CTS_TEST_LISTS_ONLY="$CTS_TEST_LISTS_ONLY}" \
            ./workloads/android/pipelines/tests/cts_execution/cts_execution.sh
          '''
          archiveArtifacts artifacts: 'cts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
        } else {
            sh 'echo "Skip Test list based on expressions"'
        }
      }
    ]
  ],
  customStageTwo: [
    [
      name: 'CTS execution',
      steps: {
        if (env.CTS_TEST_LISTS_ONLY == 'false') {
          if ( env.CUTTLEFISH_DOWNLOAD_URL &&
               currentBuild.currentResult == 'SUCCESS' ) {
            catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
              sh '''
                ANDROID_VERSION=${ANDROID_VERSION} \
                CTS_DOWNLOAD_URL="${CTS_DOWNLOAD_URL}" \
                ./workloads/android/pipelines/tests/cts_execution/cts_initialise.sh
                CTS_TESTPLAN="${CTS_TESTPLAN}" \
                CTS_MODULE="${CTS_MODULE}" \
                CTS_TIMEOUT="${CTS_TIMEOUT}" \
                SHARD_COUNT="${NUM_INSTANCES}" \
                ./workloads/android/pipelines/tests/cts_execution/cts_execution.sh
              '''
              archiveArtifacts artifacts: 'cts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              archiveArtifacts artifacts: 'android-cts-results/invocation_summary.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              archiveArtifacts artifacts: 'android-cts-results/*.zip', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
            }
          } else {
            sh 'echo "Skip CTS execution based on expressions"'
          }
        }
      }
    ]
  ]
)
