// Copyright (c) 2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// Jenkins pipeline to manage Cloud Spanner backup schedules for ABFS environments.
// - Actions supported via BACKUP_SCHEDULE_ACTION: DETAILS, CREATE, UPDATE, DELETE
// - Optional filter: ABFS_DB_NAME to target specific instance(s)
// - CREATE/UPDATE require: BACKUP_SCHEDULE_ID, CRON, RETENTION_DURATION (seconds)
// The script uses strict mode and safe loops; all gcloud commands should run with
// appropriate IAM.

pipeline {

  agent none

  environment {

    // Define Pod Template in environment so we can override storageClassName.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      spec:
        hostname: jenkins-abfs-spanner-backups-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: abfs-spanner-backups
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${INFRA_DOCKER_ARTIFACT_PATH_NAME}:${INFRA_IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sleep
          args:
          - 5h
          tty: true
    """.stripIndent()
  }



  stages {
    stage ('Start Instance') {
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Spanner Backup') {
          steps {
            script {
              currentBuild.description = "Action: ${env.BACKUP_SCHEDULE_ACTION}" + "<br/>" + "$BUILD_USER"
            }
            container(name: 'abfs-spanner-backups') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd ./workloads/android/pipelines/environment/abfs/server_administration/update_spanner_backups/
                  BACKUP_SCHEDULE_ACTION=${BACKUP_SCHEDULE_ACTION} \
                  BACKUP_SCHEDULE_ID=${BACKUP_SCHEDULE_ID} \
                  CRON=${CRON} \
                  DATABASE=${DATABASE} \
                  RETENTION_DURATION=${RETENTION_DURATION} \
                  ./update_spanner_backups.sh
                '''
              }
            }
          }
        }
      }
    }
  }
}
