apiVersion: v1
kind: ConfigMap
metadata:
  name: gerrit-mcp-server-config
data:
  gerrit_config.json: |-
    {{ .Values.server.config.json | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit-mcp-server
  template:
    metadata:
      labels:
        app: gerrit-mcp-server
    spec:
      containers:
        - name: gerrit-mcp-server
          image: {{ .Values.config.gitops.gerritMcpServer }}
          ports:
            - containerPort: {{ .Values.server.port }}
          volumeMounts:
            - name: config
              mountPath: "/app/gerrit-mcp-server/gerrit_config.json"
              subPath: gerrit_config.json
      volumes:
        - name: config
          configMap:
            name: gerrit-mcp-server-config
      env:
        - name: GERRIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: jenkins-gerrit-http-password
              key: username
        - name: GERRIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jenkins-gerrit-http-password
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-mcp-server
spec:
  type: ClusterIP
  ports:
    - port: 6322
      targetPort: {{ .Values.server.port }}
  selector:
    app: gerrit-mcp-server
